### ISSUE TITLE
버튼으로 배속 조정시 정수 1배속으로 조정하는 것이 불가능합니다.

### ISSUE THREAD

**Issue by sh827kim** [eggplantiny/yt-looper#1]
안녕하세요,
제목 그대로 버튼으로 배속 조정시 정수 1배속으로 조정하는것이 불가능합니다.
1.1 에서 - 버튼을 누르면 1.9가 됩니다.
그리고 1.1 -> 1.9 변경 케이스가 다른 경우들과 동일하게 - 버튼을 눌렀을 때 0.01 단위로 바뀌거나 차라리 최대값인 2 로 변경되는 등의 일관성도 유지되면 좋을 것 같습니다.
감사합니다.

**Comment by eggplantiny** [comment]
수정된것 같은데 확인 부탁드립니다.
